---
- name: Create Supporting Folders
  ansible.builtin.include_tasks: prep.yml

- name: Deploy Unbound Container
  ansible.builtin.include_tasks: deploy.yml

- name: Add Refres Script for Root Hints
  ansible.builtin.include_tasks: refresh.yml

- name: Check Container is working
  ansible.builtin.include_tasks: verify.yml
