---
all:
  hosts:
    vagrant-pihole-01:
      ansible_host: 192.168.56.4
      ansible_port: 22
      priority: 110
      keepalive_role: MASTER
    vagrant-pihole-02:
      ansible_host: 192.168.56.5
      ansible_port: 22
      priority: 100
      keepalive_role: BACKUP
  vars:
    ansible_user: vagrant
    ansible_password: vagrant  # only used on first run
    password_lock: false  # Change to false if you still wish to login via passwd auth
    ansible_user_home_dir: /home/{{ ansible_user }}
    ansible_python_interpreter: /usr/bin/python3
    github_user_for_ssh_key: steveyminecraft  # Change me to required value
    pihole_image: "pihole/pihole:latest"
    timezone: "Europe/London"
    webport_http: '80'  # Port for HTTP-Requests to Webinterface.
    webport_https: '443'  # Port for HTTPS-DoH Requests.
    firewall_deploy: true  # will ensure firewalld is install and configured
    DHCP_ACTIVE: false
    pihole_environment_variables:
      TZ: "{{ timezone }}"
      FTLCONF_MAXDBDAYS: "180"
      FTLCONF_webserver_api_password: 'Intranet'  # example value, change it and better use ansible-vault
      FTLCONF_dns_listeningMode: "all"
      DHCP_ACTIVE: false
      REV_SERVER: false
      REV_SERVER_CIDR: "192.168.56.0/24"
      REV_SERVER_TARGET: "192.168.56.1"
    pihole_ha_mode: true
    pihole_vip_ipv4: "192.168.56.10/24"
    pihole_vip_ipv6: "fd00::10/64"
    dnsmasq_listening: single
    pihole_container_name: pihole
    vagrant_env: true
    docker_users: vagrant
    nebula_sync_container_name: nebula
    nebula_sync_primary_url: "http://192.168.56.4"
    nebula_sync_primary_password: "{{ pihole_environment_variables.FTLCONF_webserver_api_password }}"
    nebula_sync_replicas:
      - url: "http://192.168.56.5"
        password: '{{ pihole_environment_variables.FTLCONF_webserver_api_password }}'
    nebula_sync_full_sync: true
    nebula_sync_cron: "*/15 * * * *"
    nebula_sync_dir: "/opt/nebula"
    pihole_upstream_dns: "{{ unbound_container_name }}#{{ unbound_port }}"
    pihole_network_name: "{{ unbound_network_name }}"
    pihole_network_external: true
