---
all:
  hosts:
    pihole-no-unbound:
      ansible_host: 192.168.56.6
      ansible_port: 22
      priority: 100
      keepalive_role: MASTER
  vars:
    ansible_user: vagrant
    ansible_password: vagrant
    ansible_user_home_dir: /home/vagrant
    ansible_python_interpreter: /usr/bin/python3
    ansible_ssh_common_args: "-F /dev/null -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null"
    github_user_for_ssh_key: steveyminecraft
    password_lock: false
    timezone: Europe/London
    vagrant_env: true
    pihole_ha_mode: false
    pihole_vip_ipv4: 192.168.56.7/24
    pihole_enable_unbound: false
    pihole_upstream_resolvers:
      - "1.1.1.1"
      - "1.0.0.1"
    pihole_environment_variables:
      TZ: Europe/London
      FTLCONF_webserver_api_password: "LabOnly-No-Unbound-Password!"
      FTLCONF_dns_listeningMode: "all"
      DHCP_ACTIVE: false
      REV_SERVER: false
    pihole_compose_dir: /opt/pihole
    pihole_network_name: dns_net
    unbound_container_name: unbound
    docker_group_users:
      - vagrant
    docker_daemon_dns:
      - "1.1.1.1"
      - "8.8.8.8"
    pihole_docker_dns:
      - "1.1.1.1"
      - "8.8.8.8"
