---
- name: Restart unbound stack
  community.docker.docker_compose_v2:
    project_src: "{{ unbound_compose_dir }}"
    files:
      - "{{ unbound_compose_file }}"
    state: present
    pull: missing
    recreate: always
