# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.define "pihole-no-unbound" do |node|
    node.vm.hostname         = "pihole-no-unbound"
    node.vm.box              = "bento/ubuntu-24.04"
    node.vm.box_check_update = false

    node.vm.provider "virtualbox" do |v, override|
      v.memory = 2048
      v.cpus   = 2
      override.vm.network "private_network",
                          ip: "192.168.56.6",
                          netmask: "255.255.255.0",
                          auto_config: true
    end

    if Vagrant.has_plugin?("vagrant-libvirt")
      node.vm.provider "libvirt" do |l, override|
        l.memory = 2048
        l.cpus   = 2
        l.driver = "kvm"
        override.vm.network "private_network",
                            ip: "192.168.121.6",
                            netmask: "255.255.255.0",
                            auto_config: true,
                            libvirt__network_name: "vagrant-56",
                            libvirt__mgmt_network: "none"
      end
    end
  end
end
