---
- name: Update apt packages
  ansible.builtin.apt:
    force_apt_get: true
    autoclean: true
    autoremove: true
    update_cache: true
    upgrade: dist
  when: ansible_facts['os_family'] == 'Debian'

- name: Clean DNF cache (RedHat family)
  ansible.builtin.command: dnf clean all
  changed_when: false
  when: ansible_facts['os_family'] == 'RedHat'

- name: Upgrade DNF packages (RedHat family)
  ansible.builtin.dnf:
    name: "*"
    state: latest  # noqa package-latest
    update_cache: true
    lock_timeout: 300
  when: ansible_facts['os_family'] == 'RedHat'

- name: Updates Reboot
  stat:
    path: /var/run/reboot-required
  register: updates_reboot_required

- name: Reboot
  reboot:
  when: updates_reboot_required.stat.exists
