---
galaxy_info:
  role_name: sshd
  author: your_name
  description: Harden OpenSSH server configuration.
  license: MIT
  min_ansible_version: "2.14"
  platforms:
    - name: Debian
      versions: ["all"]
    - name: Ubuntu
      versions: ["all"]
  galaxy_tags:
    - sshd
    - security

dependencies: []
