---
- name: Converge — docker role only
  hosts: all
  become: true
  gather_facts: true
  vars:
    docker_manage_iptables: false
    docker_enable_ip_forward: true
  roles:
    - role: steveyminecraft.pihole.docker
