---
- name: Create test platforms (Vagrant)
  hosts: localhost
  connection: local
  gather_facts: false
  tasks:
    - name: Start Vagrant environment for this scenario
      ansible.builtin.command: vagrant up
      args:
        chdir: "{{ playbook_dir }}"
      changed_when: true
