---
- name: Restart traefik stack
  community.docker.docker_compose_v2:
    project_src: "{{ traefik_compose_dir }}"
    files:
      - "{{ traefik_compose_file }}"
    state: present
    pull: missing
    recreate: always
