---
# molecule/default/molecule.yml
dependency:
  name: galaxy
  options:
    role-file: requirements.yaml
driver:
  name: vagrant
  provider:
    name: virtualbox
platforms:
  - name: vagrant-pihole-01
    box: bento/debian-12
    hostname: vagrant-pihole-01
    interfaces:
      - network_name: private_network
        type: static
        ip: 192.168.56.6
    memory: 2048
    cpus: 2
  - name: vagrant-pihole-02
    box: bento/debian-12
    hostname: vagrant-pihole-02
    interfaces:
      - network_name: private_network
        type: static
        ip: 192.168.56.7
        memory: 2048
    cpus: 2

provisioner:
  name: ansible
  options:
    vvv: true
  connection_options:
    ansible_ssh_user: vagrant
    ansible_password: vagrant
    ansible_become: true
  inventory:
    links:
      hosts: ../default/inventory.yml
      #group_vars: ../../group_vars/
      #host_vars: ../../host_vars/
  playbooks:
    converge: ../../playbooks/bootstrap-pihole.yaml
  env:
    ANSIBLE_ROLES_PATH: molecule/default/roles:../../roles/
verifier:
  name: ansible
scenario:
  name: debian
  test_sequence:
    - dependency
    - create
    - prepare
    - converge
    - verify
    - destroy

