---
- name: Update pi
  hosts: all
  become: true
  serial: 1
  roles:
    - role: steveyminecraft.pihole.stop_keepalived
      tags: [stopkeepalived, drain, ha]
    - role: steveyminecraft.pihole.updates
      tags: [updates, system]
    - role: steveyminecraft.pihole.pihole
      tags: [pihole, dns]
    - role: steveyminecraft.pihole.start_keepalived
      tags: [startkeepalived, resume, ha]
