---
- name: Update pi
  hosts: all
  become: true
  serial: 1
  roles:
    - role: stop_keepalived
      tags: [stopkeepalived, drain, ha]
    - role: updates
      tags: [updates, system]
    - role: pihole
      tags: [pihole, dns]
    - role: start_keepalived
      tags: [startkeepalived, resume, ha]
